# Generated by Django 5.2.8 on 2025-11-14 15:06

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, unique=True)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='refresh_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, unique=True)),
        ),
    ]
