# Generated by Django 6.0.1 on 2026-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appuser_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='favourite_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appuser',
            name='stats_retrieved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
